import {Item,Occasion,Outfit,Season} from '../types';
export type Template={name:string;required:Record<string,string[]>;optional:Record<string,string[]>};
export const TEMPLATES:Template[]=[
{name:'Western',required:{top:['Tops'],bottom:['Bottoms'],footwear:['Footwear']},optional:{outerwear:['Outerwear'],accessory:['Accessories']}},
{name:'Western dress',required:{dress:['Dresses'],footwear:['Footwear']},optional:{outerwear:['Outerwear'],accessory:['Accessories']}},
{name:'Kurta look',required:{top:['Ethnic'],bottom:['Bottoms','Ethnic'],footwear:['Footwear']},optional:{dupatta:['Ethnic'],jacket:['Ethnic'],accessory:['Accessories']}},
{name:'Saree look',required:{saree:['Ethnic'],blouse:['Ethnic'],footwear:['Footwear']},optional:{accessory:['Accessories']}},
{name:'Salwar/lehenga set',required:{set:['Ethnic'],dupatta:['Ethnic'],footwear:['Footwear']},optional:{accessory:['Accessories']}},
{name:'Indo-western',required:{top:['Ethnic'],bottom:['Bottoms'],footwear:['Footwear']},optional:{outerwear:['Outerwear'],accessory:['Accessories']}}
];
const sub=(i:Item)=>i.subcategory; const compatible=(slot:string,i:Item,t:Template)=>{if(t.name==='Western'&&slot==='top')return i.category==='Tops'; if(t.name==='Western'&&slot==='bottom')return i.category==='Bottoms'; if(t.name==='Western'&&slot==='footwear')return i.category==='Footwear'; if(t.name==='Western dress'&&slot==='dress')return i.category==='Dresses'; if(t.name==='Kurta look'&&slot==='top')return ['kurta','kurti'].includes(sub(i)); if(t.name==='Kurta look'&&slot==='bottom')return ['jeans','palazzo','churidar','leggings','trousers'].includes(sub(i)); if(t.name==='Kurta look'&&slot==='footwear')return i.category==='Footwear'; if(t.name==='Kurta look'&&slot==='dupatta')return sub(i)==='dupatta'; if(t.name==='Kurta look'&&slot==='jacket')return sub(i)==='nehru jacket'; if(t.name==='Saree look'&&slot==='saree')return sub(i)==='saree'; if(t.name==='Saree look'&&slot==='blouse')return sub(i)==='blouse'; if(t.name==='Salwar/lehenga set'&&slot==='set')return ['salwar set','lehenga'].includes(sub(i)); if(t.name==='Salwar/lehenga set'&&slot==='dupatta')return sub(i)==='dupatta'; if(t.name==='Indo-western'&&slot==='top')return ['kurta','kurti'].includes(sub(i)); if(t.name==='Indo-western'&&slot==='bottom')return ['jeans','trousers'].includes(sub(i)); if(t.name==='Indo-western'&&slot==='footwear')return ['sneakers','flats'].includes(sub(i)); if(slot==='footwear')return i.category==='Footwear'; if(slot==='outerwear')return i.category==='Outerwear'; if(slot==='accessory')return i.category==='Accessories'; return false;};
const occasionFit=(i:Item,o:Occasion)=>i.occasions.includes(o); const seasonFit=(i:Item,s:Season)=>i.seasons.includes(s);
const harmony=(a:string[],b:string[])=>{const neutral=['black','white','cream','beige','navy','brown','grey','silver','gold']; if(a.some(x=>neutral.includes(x))||b.some(x=>neutral.includes(x)))return 2; if(a.some(x=>b.includes(x)))return 2; const pairs:[string,string][]=[['blue','orange'],['pink','green'],['purple','yellow'],['red','green']]; if(a.some(x=>b.some(y=>pairs.some(([p,q])=>(p===x&&q===y)||(q===x&&p===y)))))return 1; return -2;};
export function generateOutfits(items:Item[],occasion:Occasion,season:Season,limit=4,seed=Math.random()):Outfit[]{const eligible=items.filter(i=>i.status==='clean'&&seasonFit(i,season)&&occasionFit(i,occasion)); const occasionTemplates=TEMPLATES.filter(t=>t.name==='Indo-western'&&['college','casual outing'].includes(occasion)||t.name!=='Indo-western'); const results:Outfit[]=[];
for(const t of occasionTemplates){const slots:Record<string,Item[]>= {}; for(const [slot] of Object.entries(t.required))slots[slot]=eligible.filter(i=>compatible(slot,i,t)); for(const [slot] of Object.entries(t.optional))slots[slot]=eligible.filter(i=>compatible(slot,i,t)); if(Object.values(slots).some(a=>a.length===0))continue;
const keys=Object.keys(t.required); const combos=(idx:number,chosen:Record<string,Item[]>):Record<string,Item[]>[]=>{if(idx===keys.length)return[chosen];const k=keys[idx];return slots[k].slice(0,8).flatMap(i=>combos(idx+1,{...chosen,[k]:[i]}));};
for(const c of combos(0,{})){const all=Object.values(c).flat(); if(new Set(all.map(x=>x.id)).size!==all.length)continue; let score=0; for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++)score+=harmony(all[i].colors,all[j].colors); const avg=all.reduce((a,x)=>a+x.formality,0)/all.length; score-=Math.abs(avg-(occasion==='office'||occasion==='wedding guest'||occasion==='Diwali'||occasion==='puja'?4:2.5))*1.5; score+=all.filter(x=>x.favorite).length*.7; score-=all.reduce((a,x)=>a+Math.min(x.timesWorn,6),0)*.08; score+=(seed-.5)*.5; const why=score>4?'Balanced colors with a strong, versatile base.':score>1?'Easy color pairing with consistent formality.':'A relaxed mix with a simple focal piece.'; results.push({template:t.name,slots:c,score,why}); }
}
const sorted=results.sort((a,b)=>b.score-a.score); const out:Outfit[]=[]; const main=(o:Outfit)=>Object.values(o.slots)[0]?.[0]?.id; for(const o of sorted)if(!out.some(x=>main(x)===main(o)))out.push(o); return out.slice(0,limit);}
export function simulateBuy(items:Item[],candidate:Item,occasionList:Occasion[],season:Season){const before=new Set(occasionList.flatMap(o=>generateOutfits(items,o,season,100,0).map(o=>signature(o))));const after=new Set(occasionList.flatMap(o=>generateOutfits([...items,candidate],o,season,100,0).map(o=>signature(o)))); return [...after].filter(x=>!before.has(x)).length;}
export const signature=(o:Outfit)=>Object.values(o.slots).flat().map(i=>i.id).sort().join('|');
